//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public int IdStudent { get; set; }
        public int IdEvent { get; set; }
        public int Count { get; set; }
        public string Position { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Students Students { get; set; }
    }
}
